name: ç’°å¢ƒæ§‹ç¯‰
description: ç’°å¢ƒæ§‹ç¯‰ãƒ»è¨­å®šå‘¨ã‚Šã®ã‚¿ã‚¹ã‚¯
title: 'ğŸ”§ environment: '
body:
  - type: textarea
    id: overview
    attributes:
      label: æ¦‚è¦
      description: ç’°å¢ƒæ§‹ç¯‰ã®æ¦‚è¦ã‚’è¨˜è¼‰ã—ã¦ãã ã•ã„
    validations:
      required: true
  - type: textarea
    id: todo
    attributes:
      label: ã‚¿ã‚¹ã‚¯
      description: ã‚¿ã‚¹ã‚¯ã‚’è¨˜è¼‰ã—ã¦ãã ã•ã„
      value: |
        - [ ]
        - [ ]
    validations:
      required: true
  - type: textarea
    id: module
    attributes:
      label: è¿½åŠ ã™ã‚‹ãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ«
      description: è¿½åŠ ã™ã‚‹ãƒ¢ã‚¸ãƒ¥ãƒ¼ãƒ«ã‚’è¨˜è¼‰ã—ã¦ãã ã•ã„
      value: |
        - 
        - 
  - type: textarea
    id: note
    attributes:
      label: å‚™è€ƒ
      description: ç’°å¢ƒæ§‹ç¯‰ãƒ»è¨­å®šã«é–¢ã™ã‚‹å‚™è€ƒã‚’è¨˜è¼‰ã—ã¦ãã ã•ã„
      placeholder:
